name: GitHub CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      REMIX_LICENSE_KEY: ${{ secrets.REMIX_LICENSE_KEY }}

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - run: npm run lint
      - run: npm test
        env:
          CI: true
      - run: npm run build
